### ISSUE TITLE
设置header

### ISSUE THREAD

**Issue by burgess666** [alingse/jsoncsv#10]
你好，感谢你分享这个repo。请问如何把key作为csv文件中的header。
{"abstract": "xxxxx", "authors": ["a", "b", "c"], "references": ["1", "2"], "title": "aaaaa"}

abstract    authors1    author2       author3    references1   reference2            title 
 xxxxx           a                  b                  c                 1                      2                  aaaaa

谢谢！

**Comment by alingse** [comment]
你好。这里直接输出就会是 csv 文件的，默认使用 ","  进行分隔。

```
➜  ~ echo '{"abstract": "xxxxx", "authors": ["a", "b", "c"], "references": ["1", "2"], "title": "aaaaa"}'|jsoncsv |mkexcel > output.csv
➜  ~ cat output.csv
references.0,references.1,authors.1,authors.0,title,abstract,authors.2
1,2,b,a,aaaaa,xxxxx,c
➜  ~ 

```

**Comment by alingse** [comment]
这里暂时不支持对 key 进行筛选。之后会做的。

**Comment by burgess666** [comment]
谢谢！

**Comment by alingse** [comment]
可以用 jq 来删除控制 header

echo "{"a":1, "b":2}"|jq -c 'del(.b)'
