### ISSUE TITLE
中文windows 7 64位+python3.6.5 环境下pip安装(2.0.7版)失败

### ISSUE THREAD

**Issue by royqh1979** [alingse/jsoncsv#16]
C:\Users\Roy>pip install jsoncsv
Collecting jsoncsv
  Downloading https://files.pythonhosted.org/packages/a1/31/eb4c78c2f9a57ac29ff6
2b12a3c7a5cb48b762b7c0362b6c4a152b721d7c/jsoncsv-2.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Roy\AppData\Local\Temp\pip-install-jblltyy7\jsoncsv\setup.p
y", line 12, in <module>
        readme = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 1115: ill
egal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Roy\AppD
ata\Local\Temp\pip-install-jblltyy7\jsoncsv\

**Comment by alingse** [comment]
啊，我还没支持 py3，另外这里不知道为啥会有gbk 编码，等我查查

**Comment by royqh1979** [comment]
中文windows缺省是gbk编码,大概read()用的是系统缺省编码?

**Comment by royqh1979** [comment]
哦, 最好在说明里写一下还不支持python 3

**Comment by alingse** [comment]
@royqh1979  今天会支持一下

**Comment by royqh1979** [comment]
谢谢!

**Comment by lzfy** [comment]
修改一下setup.py，用utf-8打开文件就可以了

**Comment by alingse** [comment]
@royqh1979  发了 2.0.8b0 版本，应该可以支持 windows 安装了，不过暂时还不支持 python3（需要做的还很多）

感谢 @lzfy 

等我有空了修一下兼容支持 python2 python3

**Comment by alingse** [comment]
修了一下 unicode、utf8 等相关的，暂时支持 python2 + windows 了

python3 的支持还要再做，等好了再 close

**Comment by alingse** [comment]
@royqh1979  @lzfy 
改了一些地方，加了 支持 python3 的版本，2.0.9
